Feat/2 styled components
lysycyn/adidas-shop-frontend pull request #5
Opened 2017-05-13 00:03 UTC by lysycyn

Сделал главную страницу. Не могу понять, почему не срабатывает свойство inCard в карточке товара, это нужно для того, чтобы абсолютить sale для каждой карточки, где это нужно

2017-05-13 08:59 UTC, lysycyn commented
Жень, у меня какая-то хрень с 2 вещами.
1. В сайдбаре на активном урле не срабатывает цвет
2. В details я не могу юзать sale и BigImage

2017-05-13 10:02 UTC, evgenyrodionov commented
Все вопросы в чат

2017-05-13 10:05 UTC, imevro requested changes
Норм, только выкинь injectGlobal styled-components, напиши обычным цсс

2017-05-13 10:05 UTC, evgenyrodionov commented on src/App.js
> +import "./styled-components/global"
Нет, зачем это? Сделай нормальный цсс.

Правила импортов http://telegra.ph/6a640335-fcfd-4e53-b0d9-25cd145cb565-05-12

2017-05-13 10:05 UTC, evgenyrodionov commented
Ну и мердж конфликты надо править)

2017-05-13 18:53 UTC, imevro requested changes
Фикси и еслинт фикси

2017-05-13 18:53 UTC, evgenyrodionov commented on src/Details/index.js
> +import Sale from "../components/Sale"
Нет

2017-05-13 18:53 UTC, evgenyrodionov commented on src/Details/index.js
> +import Sale from "../components/Sale"
Почему в этой директории

2017-05-13 18:53 UTC, evgenyrodionov commented on src/Details/index.js
> +import Sale from "../components/Sale"
Зачем нам компонентс если всё приложение компонентс

2017-05-14 14:05 UTC, imevro requested changes
Фикси

2017-05-14 14:05 UTC, evgenyrodionov commented on src/components/Sale/index.jsx
> +  ${props => props.inCard && `
Неа, сноси нахуй, этот компонент не должен знать про позиционирование вообще ничего, позиционирование делаешь внутри карточки/товара отдельным родительским компонентом

2017-05-14 14:05 UTC, evgenyrodionov commented on src/components/Sale/index.jsx
> +  ${props => props.inDetails && `
Тоже самое

2017-05-14 16:55 UTC, lysycyn commented
Добавил проект на surge. Поправил компоненты, верстку (что успел)

2017-05-14 18:05 UTC, imevro requested changes
Не проверяю пока не будет нормальная вёрстка

2017-05-14 21:42 UTC, imevro approved these changes
Пофикси и норм

2017-05-14 21:42 UTC, evgenyrodionov commented on package.json
> +    "eslint-plugin-jsx-a11y": "4.0.0",
Выкинь из депс

2017-05-14 21:42 UTC, evgenyrodionov commented on src/List/Filter/styled.js
> +  width: 4.586rem;
откуда блядь опять эти меджик намберс

2017-05-14 21:42 UTC, evgenyrodionov commented on src/List/Filter/styled.js
> +  width: 4.586rem;
убирали же

2017-05-15 10:01 UTC, imevro requested changes
Жду исправлений в отдельном бранче

2017-05-15 10:01 UTC, evgenyrodionov commented on package.json
> +    "eslint-plugin-jsx-a11y": "4.0.0",
И?

2017-05-15 21:14 UTC, imevro requested changes
Неплохо, но пофикси

2017-05-15 21:14 UTC, evgenyrodionov commented on src/Products/Show/Gallery/BigImage.jsx
> +    <Col xs={12} md={10} lg={9}>
Вытащи сетку отсюда

2017-05-15 21:14 UTC, evgenyrodionov commented on src/Products/Show/Header/Price.jsx
> +    margin-top: -4rem;
Отрицательные марджины зло

2017-05-15 21:14 UTC, evgenyrodionov commented on src/Products/Show/Header/Price.jsx
> +  margin-top: -18rem;
Отрицательные марджины зло

2017-05-16 09:31 UTC, evgenyrodionov commented on src/Products/Show/Gallery/BigImage.jsx
> +    <Col xs={12} md={10} lg={9}>
Ну?

2017-05-16 09:32 UTC, imevro requested changes
От сетки избавься

2017-05-16 13:31 UTC, merged